version: '3.7'
services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    restart: unless-stopped
    command: nginx -g 'daemon off;'
    network_mode: host
    # ports:
    #   - 80:80
    volumes:
      - ./etc-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./etc-nginx/conf.d:/etc/nginx/conf.d:ro